In [70]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pickle
from sklearn.linear_model import LogisticRegression

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

%matplotlib inline
import seaborn as sns

In [52]:
all_data=pd.read_csv('heart_failure_clinical_records_dataset.csv')
all_data.head()

age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0  75.0        0                       582  ...        0     4            1
1  55.0        0                      7861  ...        0     6            1
2  65.0        0                       146  ...        1     7            1
3  50.0        1                       111  ...        0     7            1
4  65.0        1                       160  ...        0     8            1

[5 rows x 13 columns]

In [26]:
all_data.tail()

age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
294  62.0        0                        61  ...        1   270            0
295  55.0        0                      1820  ...        0   271            0
296  45.0        0                      2060  ...        0   278            0
297  45.0        0                      2413  ...        1   280            0
298  50.0        0                       196  ...        1   285            0

[5 rows x 13 columns]

In [53]:
x=all_data.drop(columns='DEATH_EVENT')
y=all_data['DEATH_EVENT']

In [7]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: DEATH_EVENT, dtype: int64

In [54]:
x.head()  

age  anaemia  creatinine_phosphokinase  ...  sex  smoking  time
0  75.0        0                       582  ...    1        0     4
1  55.0        0                      7861  ...    1        0     6
2  65.0        0                       146  ...    1        1     7
3  50.0        1                       111  ...    1        0     7
4  65.0        1                       160  ...    0        0     8

[5 rows x 12 columns]

In [55]:

x=x.drop(columns='time')

In [56]:
x.head()

age  anaemia  creatinine_phosphokinase  ...  serum_sodium  sex  smoking
0  75.0        0                       582  ...           130    1        0
1  55.0        0                      7861  ...           136    1        0
2  65.0        0                       146  ...           129    1        1
3  50.0        1                       111  ...           137    1        0
4  65.0        1                       160  ...           116    0        0

[5 rows x 11 columns]

In [57]:
X_train, X_test, y_train ,y_test =train_test_split(x,y,test_size=0.3)

In [58]:
model= RandomForestClassifier()

In [59]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [60]:
y_pred=model.predict(X_test)

In [61]:
accuracy =accuracy_score(y_test,y_pred)

In [62]:
accuracy

0.6777777777777778

In [63]:
model1.predict([[51,1,555,1,22,1,334000,1.5,123,0,1]])

array([1])

In [64]:
accureses=[]
top_acc=0
for i in range(50):
  X_train ,X_test , y_train ,y_test = train_test_split(x,y,test_size=0.3)
  model1 = RandomForestClassifier()
  model1.fit(X_train,y_train)
  y_pred = model1.predict(X_test)
  accuracy =accuracy_score(y_test,y_pred)
  accureses.append(accuracy)
  if accuracy>top_acc:
    top_acc=accuracy
    with open('heart_failure.pickle','wb') as file:
      pickle.dump(model1,file)
print(top_acc)
print(accureses)

0.8222222222222222
[0.8222222222222222, 0.6888888888888889, 0.7777777777777778, 0.7, 0.7777777777777778, 0.7555555555555555, 0.6888888888888889, 0.6777777777777778, 0.7333333333333333, 0.6666666666666666, 0.6888888888888889, 0.7333333333333333, 0.7666666666666667, 0.7222222222222222, 0.7222222222222222, 0.7888888888888889, 0.6666666666666666, 0.6888888888888889, 0.7111111111111111, 0.7888888888888889, 0.8, 0.7777777777777778, 0.7111111111111111, 0.7111111111111111, 0.7222222222222222, 0.7222222222222222, 0.7777777777777778, 0.7111111111111111, 0.6555555555555556, 0.6888888888888889, 0.7111111111111111, 0.7, 0.7444444444444445, 0.7111111111111111, 0.7777777777777778, 0.7888888888888889, 0.7777777777777778, 0.7111111111111111, 0.7777777777777778, 0.6888888888888889, 0.7222222222222222, 0.7666666666666667, 0.7777777777777778, 0.7555555555555555, 0.7, 0.6888888888888889, 0.7111111111111111, 0.6888888888888889, 0.7444444444444445, 0.7333333333333333]


In [65]:
model_test =pickle.load(open('heart_failure.pickle','rb'))


In [66]:
model_test.predict([[51,1,555,1,22,1,334000,1.5,123,0,1]])

array([1])

In [51]:
X_train.head()

age  anaemia  creatinine_phosphokinase  ...  serum_sodium  sex  smoking
156  52.000        1                        58  ...           136    0        0
207  85.000        0                       212  ...           136    1        0
219  55.000        0                       582  ...           140    0        0
143  61.000        1                        84  ...           141    0        0
185  60.667        1                       104  ...           136    1        0

[5 rows x 11 columns]

In [71]:
accureses=[]
top_acc=0
for i in range(50):
  X_train ,X_test , y_train ,y_test = train_test_split(x,y,test_size=0.3)
  model2 = LogisticRegression()
  model2.fit(X_train,y_train)
  y_pred = model1.predict(X_test)
  accuracy =accuracy_score(y_test,y_pred)
  accureses.append(accuracy)
  if accuracy>top_acc:
    top_acc=accuracy
    with open('heart_failure2.pickle','wb') as file:
      pickle.dump(model1,file)
print(top_acc)
print(accureses)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.9777777777777777
[0.9333333333333333, 0.9111111111111111, 0.9555555555555556, 0.9, 0.9333333333333333, 0.9, 0.9, 0.9333333333333333, 0.9333333333333333, 0.8888888888888888, 0.9444444444444444, 0.9111111111111111, 0.9666666666666667, 0.8888888888888888, 0.8888888888888888, 0.9333333333333333, 0.9, 0.8777777777777778, 0.9444444444444444, 0.8888888888888888, 0.9111111111111111, 0.9333333333333333, 0.9111111111111111, 0.9222222222222223, 0.9777777777777777, 0.9555555555555556, 0.9, 0.9333333333333333, 0.9, 0.8888888888888888, 0.9, 0.9, 0.9333333333333333, 0.8666666666666667, 0.9333333333333333, 0.9555555555555556, 0.9444444444444444, 0.9222222222222223, 0.8666666666666667, 0.9111111111111111, 0.8888888888888888, 0.9222222222222223, 0.9333333333333333, 0.9111111111111111, 0.9333333333333333, 0.9444444444444444, 0.9222222222222223, 0.9555555555555556, 0.9111111111111111, 0.9333333333333333]


In [72]:
model_test2 =pickle.load(open('heart_failure.pickle','rb'))

In [73]:
model_test2.predict([[51,1,555,1,22,1,334000,1.5,123,0,1]])

array([1])